"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.INITIAL_BALL_SPEED = exports.LOSE_SCORE = exports.PADDLE_SPEED = exports.BALL_RADIUS = exports.PADDLE_HEIGHT = exports.PADDLE_WIDTH = exports.CANVAS_HEIGHT = exports.CANVAS_WIDTH = void 0;
exports.CANVAS_WIDTH = 800;
exports.CANVAS_HEIGHT = 600;
exports.PADDLE_WIDTH = 100;
exports.PADDLE_HEIGHT = 15;
exports.BALL_RADIUS = 10;
exports.PADDLE_SPEED = 8;
exports.LOSE_SCORE = 5;
exports.INITIAL_BALL_SPEED = 5;
