export enum GameTypeEnum
{
    SINGLEPLAYER = "SINGLEPLAYER",
    MULTIPLAYER_LOCAL = "MULTIPLAYER_LOCAL",
    MULTIPLAYER_REMOTO = "MULTIPLAYER_REMOTO",
    TOURNAMENT = "TOURNAMENT",
    RPS = "RPS"
}