# Generated by Django 5.1.4 on 2024-12-19 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_customuser_is_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2024, 12, 19, 1, 42, 17, 578115, tzinfo=datetime.timezone.utc)),
        ),
    ]
