# Generated by Django 5.1.4 on 2024-12-19 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_customuser_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2024, 12, 19, 14, 14, 44, 167066, tzinfo=datetime.timezone.utc)),
        ),
    ]
