# Generated by Django 5.1.4 on 2025-01-07 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_customuser_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2025, 1, 7, 21, 50, 55, 902688, tzinfo=datetime.timezone.utc)),
        ),
    ]
