name: CI/CD pipeline
on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]

jobs:
    build-check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  cache: 'npm'

            # Setup ms
            - name: Install auth-service dependencies
              working-directory: ./auth-service
              run: npm ci

            - name: Install user-service dependencies
              working-directory: ./user-service
              run: npm ci

            - name: Install game-service dependencies
              working-directory: ./game-service
              run: npm ci

            - name: Install frontend dependencies
              working-directory: ./frontend
              run: npm ci

            #Setup docker
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build services
              run: docker compose build

            - name: Start services
              run: docker compose up -d

            - name: Check if services are running
              run: docker compose ps

            - name: Docker compose down
              if: always()
              run: docker compose down -v